[workspace]
resolver = "2"
members = ["crates/*", "playwright-tests/wasm-bindings"]

[workspace.package]
version = "0.7.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ankurah/virtual-scroll"
